version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
        patterns:
          - "*"
      development-dependencies:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"